SELECT * FROM DEPT;

-- SELECT <조회 컬럼명> FROM <테이블명>;

SELECT * FROM EMP;

SELECT * FROM SALGRADE;

SELECT * FROM BONUS;

SELECT
  e.EMPNO
  , e.ENAME
  , d.DNAME
  , d.LOC
FROM EMP e 
INNER JOIN DEPT d ON e.DEPTNO = d.DEPTNO;

SELECT 
  EMPNO 
  , ENAME 
FROM  EMP
WHERE EMPNO = 7499;

SELECT 
  *
FROM EMP
ORDER BY SAL ASC;

SELECT 
  EMPNO 
  , ENAME
  , SAL
  , DEPTNO
FROM EMP;
 
SELECT 
  EMPNO
  , ENAME
  , SAL
FROM EMP
WHERE SAL >= 3000;

SELECT 
  EMPNO
  , ENAME
  , SAL
FROM EMP
WHERE SAL >= 3000 AND SAL <= 5000;

SELECT 
  EMPNO
  , ENAME
  , SAL
FROM EMP
WHERE SAL >= 3000 OR SAL <= 1500
ORDER BY SAL DESC;        

SELECT 
  EMPNO
  , ENAME
  , SAL
FROM EMP
WHERE COMM IS NULL;

SELECT 
  EMPNO
  , ENAME
  , SAL
FROM EMP
WHERE EMPNO IN (7566,7698,7788,7900);

SELECT ENAME, UPPER(ENAME),LOWER(ENAME),INITCAP(ENAME)
FROM EMP;

SELECT 
  ENAME
  , LENGTH(ENAME)
FROM EMP;

SELECT * FROM EMP;

SELECT JOB, SUBSTR(JOB, 1, 2), SUBSTR(JOB, 3, 2), SUBSTR(JOB, 5)
FROM EMP;

SELECT 'Oracle' FROM DUAL;

SELECT 'Oracle',
       LPAD('Oracle', 10, '#') AS LPAD_1,
       RPAD('Oracle', 10, '*') AS RPAD_1,
       LPAD('Oracle', 10) AS LPAD_2,
       RPAD('Oracle', 10) AS RPAD_2
FROM DUAL;

SELECT ENAME FROM EMP;

SELECT ENAME,
       RPAD(SUBSTR(ENAME, 1, LENGTH(ENAME)-2), LENGTH(ENAME), '*') AS RPAD_1
FROM EMP;

SELECT ENAME,
       SUBSTR(ENAME, 1, LENGTH(ENAME)-2),
       RPAD(SUBSTR(ENAME, 1, LENGTH(ENAME)-2), LENGTH(ENAME), '*') AS RPAD_1
FROM EMP;

SELECT 
  EMPNO 
  , ENAME
  , COMM
  , SAL
  , NVL(COMM, 0)
  , SAL+NVL(COMM, 0)
FROM EMP;

SELECT
  sum(sal)
FROM EMP
WHERE JOB = 'MANAGER';

SELECT
  count(*)
FROM EMP
WHERE JOB = 'MANAGER';

SELECT
  count(*)
  , SUM(SAL)
  , DEPTNO 
FROM EMP
GROUP BY DEPTNO;

SELECT 
  e.EMPNO
  , e.ENAME 
  , d.DNAME 
  , d.LOC
  , d.DEPTNO
FROM EMP e
INNER JOIN DEPT d ON e.DEPTNO = d.DEPTNO;

SELECT 
  e.EMPNO
  , e.ENAME
  , e.JOB
  , e.MGR
  , e.HIREDATE
  , e.SAL
  , e.COMM
  , e.DEPTNO
  , d.DNAME 
FROM EMP e
INNER JOIN DEPT d ON e.DEPTNO = d.DEPTNO
WHERE e.SAL >= 1500
ORDER BY e.SAL DESC;

SELECT 
  e.EMPNO
  , e.ENAME
  , e.SAL
  , d.DNAME
FROM EMP e 
INNER JOIN DEPT d ON e.DEPTNO = d.DEPTNO
WHERE e.SAL >= 1500 AND e.SAL <= 3000
ORDER BY e.SAL ASC;

CREATE TABLE emp_detail
(
   tel varchar2(20),
   child number(2),
   age number(3),
   empno number(4)
      CONSTRAINT emp_detail_EMP_EMPNO_fk
         REFERENCES EMP
            ON DELETE CASCADE
)

INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO)
VALUES('01025117635', 0, 43, 7369);

SELECT * FROM EMP_DETAIL;
SELECT * FROM EMP;

INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO)
VALUES('01025117890', 1, 40, 7499);

INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO)
VALUES('01025347810', 0, 45, 7521);

INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO)
VALUES('01029517820', 1, 41, 7566);

INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO)
VALUES('01029497990', 0, 42, 7654);

SELECT * FROM EMP_DETAIL;

SELECT
  e.EMPNO
  , e.ENAME
  , e.JOB
  , ed.TEL
  , ed.CHILD
  , ed.AGE
  , d.DNAME
 FROM EMP e
 INNER JOIN EMP_DETAIL ed ON e.EMPNO = ed.EMPNO
 INNER JOIN DEPT d ON e.DEPTNO = d.DEPTNO;

SELECT
  e.EMPNO
  , e.ENAME
  , e.JOB
  , ed.TEL
  , ed.CHILD
  , ed.AGE
  , d.DNAME
 FROM EMP e
 LEFT JOIN EMP_DETAIL ed ON e.EMPNO = ed.EMPNO
 LEFT JOIN DEPT d ON e.DEPTNO = d.DEPTNO;
 
SELECT
  e.EMPNO
  , e.ENAME
  , e.JOB
  , e.MGR
  , e.HIREDATE
  , e.SAL
  , e.COMM
  , e.DEPTNO
  , d.DNAME
  , d.LOC
  , ed.TEL
  , ed.CHILD
  , ed.AGE
FROM EMP e
INNER JOIN EMP_DETAIL ed ON e.EMPNO = ed.EMPNO
INNER JOIN DEPT d ON e.DEPTNO = d.DEPTNO
WHERE ed.CHILD = 0;

SELECT 
  count(*)
FROM EMP e
LEFT JOIN EMP_DETAIL ed ON e.EMPNO = ed.EMPNO
WHERE ed.TEL IS NULL AND ed.CHILD IS NULL AND ed.AGE IS NULL;

SELECT
  AVG(NVL(e.SAL,0)) 
FROM EMP e 
INNER JOIN EMP_DETAIL ed ON e.EMPNO = ed.EMPNO;

SELECT 
  SUM(NVL(ed.CHILD,0))
FROM EMP e 
INNER JOIN DEPT d ON e.DEPTNO = d.DEPTNO
INNER JOIN EMP_DETAIL ed ON e.EMPNO = ed.EMPNO
WHERE d.LOC = 'DALLAS';

SELECT * 
FROM EMP e
INNER JOIN DEPT d ON e.DEPTNO = d.DEPTNO
INNER JOIN EMP_DETAIL ed ON e.EMPNO = ed.EMPNO;